'use strict';
const assert=require('node:assert/strict'),{initializeApp}=require('firebase-admin/app'),{getFirestore}=require('firebase-admin/firestore'),{createService,compare,snapshot}=require('../../functions/study-town/service'),D=require('../../functions/study-town/study-domain');
assert.ok(process.env.FIRESTORE_EMULATOR_HOST,'Emulator only');initializeApp({projectId:'demo-dj48-rules'});const db=getFirestore();let now=100000;const service=createService({db,now:()=>now});
(async()=>{for(const [uid,id,role] of [['study-a','study-member-a','student'],['study-b','study-member-b','student'],['study-admin','study-member-admin','admin']]){await db.collection('authLinks').doc(uid).set({memberUserId:id});await db.collection('users').doc(id).set({authUid:uid,status:'active',role,nickname:id});}
assert.ok(compare({bosses:2,rooms:12,correct:1,attempts:10},{bosses:1,rooms:11,correct:10,attempts:10})<0);
assert.ok(compare({bosses:1,rooms:8,correct:16,attempts:20},{bosses:1,rooms:8,correct:8,attempts:10})<0);assert.throws(()=>snapshot({rooms:5,bosses:1}));
await assert.rejects(service.act(null,{action:'connect'}));const a=await service.act('study-a',{action:'connect'}),b=await service.act('study-b',{action:'connect'}),admin=await service.act('study-admin',{action:'connect'});assert.equal(admin.eligible,false);await assert.rejects(service.act(null,{action:'start',token:admin.token,tier:'beginner',units:['fraction']}));
const call=(p)=>service.act(null,{token:a.token,...p});
async function play(tier,rooms,bosses,wrong=false){const {runId}=await call({action:'start',tier,units:['fraction','triangle']});for(let i=0;i<3;i++){const key='entry-1-'+i,q=await call({action:'question',runId,key});assert.deepEqual(await call({action:'question',runId,key}),q);const generated=D.generate(q.template,q.seed),answers=Object.fromEntries(generated.fields.map(f=>[f.id,f.answer]));const result=await call({action:'answer',runId,key,answers:wrong?{}:answers});assert.equal(result.correct,!wrong);assert.equal((await call({action:'answer',runId,key,answers:wrong?answers:{}})).correct,!wrong);}
const result=await call({action:'finish',runId,metrics:{rooms,bosses}});assert.deepEqual(await call({action:'finish',runId,metrics:{rooms:24,bosses:4}}),result);await assert.rejects(service.act(null,{action:'finish',token:b.token,runId,metrics:{rooms,bosses}}));return result;}
assert.equal((await play('beginner',6,1)).improved,true);assert.equal((await play('beginner',5,0)).improved,false);assert.equal((await play('intermediate',1,0)).improved,true);assert.equal((await play('advanced',1,0)).improved,true);assert.equal((await play('beginner',6,1,true)).improved,false);
const rows=(await service.act('study-a',{action:'list',tier:'beginner'})).rows;assert.equal(rows.filter(r=>r.mine).length,1);assert.equal(rows.find(r=>r.mine).rooms,6);assert.equal(rows.find(r=>r.mine).correct,3);
const {runId}=await call({action:'start',tier:'beginner',units:['decimal']});await call({action:'question',runId,key:'entry-1-0'});await assert.rejects(call({action:'answer',runId,key:'entry-1-0',answers:{x:'1'.repeat(1000)}}));await assert.rejects(call({action:'question',runId,key:'reward-5-0'}));await assert.rejects(call({action:'answer',runId,key:'not-issued',answers:{}}));
assert.equal((await call({action:'finish',runId,metrics:{rooms:0,bosses:0}})).record.attempts,0);await assert.rejects(call({action:'answer',runId,key:'entry-1-0',answers:{}}));now+=13*3600000;await assert.rejects(call({action:'start',tier:'beginner',units:['fraction']}));assert.equal(require('node:fs').readFileSync('public/fraction-world/study-domain.js','utf8'),require('node:fs').readFileSync('functions/study-town/study-domain.js','utf8'));
console.log('Study ranking PASS: identity, ownership, immutable first answer, server grading, tier-separated best, comparator, duplicate finish, pending question, expired token, admin exclusion');
})().catch(e=>{console.error(e);process.exitCode=1;});
