'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const C=require('../../public/fraction-world/content.js'),S=require('../../public/fraction-world/studio-domain.js'),T=require('../../public/fraction-world/tower-domain.js');
const E=require('../../public/fraction-world/expedition-domain');
const source=fs.readFileSync(require.resolve('../../public/fraction-world/store.js'),'utf8');
function boot(raw,blocked=false){let storage=raw;const context={window:{FWExpedition:E},FWExpedition:E,FWContent:C,localStorage:{getItem:k=>k==='dj48.study-town.v1'?storage:null,setItem:(_k,v)=>{if(blocked)throw new Error('quota');storage=v;}}};vm.runInNewContext(source,context);return {store:context.window.FWStore,getRaw:()=>storage};}
let a=boot(null);a.store.get().tower=T.create('wand');a.store.get().studio=S.create(['lumi','rio','sora']);a.store.get().stats[0]={attempts:3,first:2,solved:3};a.store.save();
let b=boot(a.getRaw());assert.equal(b.store.get().tower.weapon,'wand');assert.equal(b.store.get().studio.day,1);assert.equal(b.store.get().total,3);b.store.switchSlot(1);assert.equal(b.store.get().tower,null);b.store.switchSlot(0);assert.equal(b.store.get().tower.weapon,'wand');
const parsed=JSON.parse(a.getRaw());parsed.slots[0].studio.phase='event';parsed.slots[0].studio.event=999;parsed.slots[0].settings=null;parsed.slots[0].quiz={mode:'garbage'};parsed.slots[1]=null;
b=boot(JSON.stringify(parsed));assert.equal(b.store.get().studio,null);assert.equal(b.store.get().tower.weapon,'wand');assert.equal(b.store.get().settings.level,'all');assert.equal(b.store.get().quiz,null);assert.ok(b.store.warning());
b=boot('{bad json');assert.ok(b.store.warning());assert.equal(b.getRaw(),'{bad json');
b=boot(null,true);b.store.get().total=9;assert.equal(b.store.save(),false);assert.ok(b.store.warning());assert.equal(b.store.get().total,9);
console.log('Fraction World storage: run restore, slot isolation, partial corruption recovery, malformed JSON preservation, quota failure passed.');
const legacy=JSON.parse(a.getRaw());delete legacy.slots[0].tower.upgrades;b=boot(JSON.stringify(legacy));assert.equal(b.store.get().tower.weapon,'wand');assert.equal(Object.keys(b.store.get().tower.upgrades).length,0);
legacy.slots[0].tower.upgrades={heart:3,ember:999,unknown:2,frost:-1};legacy.slots[0].tower.hp=210;b=boot(JSON.stringify(legacy));assert.equal(b.store.get().tower.upgrades.heart,3);assert.equal(Object.keys(b.store.get().tower.upgrades).length,1);assert.equal(b.store.get().tower.hp,210);

const expanded=boot(null);expanded.store.get().tower=E.create('wand','hard','long');expanded.store.get().unlocks=['boss0'];expanded.store.save();let restored=boot(expanded.getRaw());assert.equal(restored.store.get().tower.expedition,'long');assert.equal(restored.store.get().unlocks[0],'boss0');const corrupt=JSON.parse(expanded.getRaw());corrupt.slots[0].tower.maps[0][0][0].stock[0].price=-10;restored=boot(JSON.stringify(corrupt));assert.equal(restored.store.get().tower,null);assert.equal(restored.store.get().unlocks[0],'boss0');console.log('Expedition storage: map/long mode/unlocks preserved, corrupt shop rejected without losing unlocks.');
// Reset only the confirmed active slot; a failed write must not erase progress.
const reset=boot(a.getRaw());reset.store.switchSlot(1);reset.store.get().tower=T.create('bow');reset.store.save();const other=JSON.stringify(reset.store.get());reset.store.switchSlot(0);reset.store.get().unlocks=['boss0'];reset.store.get().collection=['ember'];reset.store.get().quiz={mode:'tower-entry'};reset.store.save();const preserved=JSON.stringify({...reset.store.get(),tower:null,quiz:null});assert.equal(reset.store.discardTower(1),false);assert.equal(reset.store.discardTower(0),true);assert.equal(JSON.stringify(reset.store.get()),preserved);assert.equal(reset.store.get().tower,null);assert.equal(reset.store.resetSlot(1),false);assert.equal(reset.store.resetSlot(0),true);assert.equal(reset.store.get().total,0);assert.equal(reset.store.get().studio,null);assert.equal(reset.store.get().collection.length,0);reset.store.switchSlot(1);assert.equal(JSON.stringify(reset.store.get()),other);const reloaded=boot(reset.getRaw());assert.equal(reloaded.store.slot(),1);assert.equal(reloaded.store.get().tower.weapon,'bow');reloaded.store.switchSlot(0);assert.equal(reloaded.store.get().tower,null);assert.equal(reloaded.store.get().unlocks.length,0);
const noWrite=boot(a.getRaw(),true),beforeReset=JSON.stringify(noWrite.store.get()),storedBefore=noWrite.getRaw();assert.equal(noWrite.store.resetSlot(0),false);assert.equal(JSON.stringify(noWrite.store.get()),beforeReset);assert.equal(noWrite.getRaw(),storedBefore);assert.equal(noWrite.store.discardTower(0),false);assert.equal(JSON.stringify(noWrite.store.get()),beforeReset);
console.log('Slot reset: selected-slot isolation, tower-only preservation, reload, wrong-slot rejection and storage failure rollback passed.');

// The approved global reset touches only the legacy game namespace and runs once.
function keyedBoot(entries,blocked=false){const values=new Map(entries),context={window:{FWExpedition:E},FWExpedition:E,FWContent:C,localStorage:{getItem:k=>values.get(k)??null,setItem:(k,v)=>{if(blocked)throw Error('quota');values.set(k,v);},removeItem:k=>values.delete(k)}};vm.runInNewContext(source,context);return {store:context.window.FWStore,values};}
const wiped=keyedBoot([['dj48.fraction-world.v1',a.getRaw()],['other-app','keep']]);assert.equal(wiped.store.get().tower,null);assert.equal(wiped.store.resetNotice(),true);assert.equal(wiped.values.has('dj48.fraction-world.v1'),false);assert.equal(wiped.values.get('other-app'),'keep');wiped.store.get().tower=E.create('bow','hard');wiped.store.save();const resumed=keyedBoot(wiped.values);assert.equal(resumed.store.get().tower.weapon,'bow');assert.equal(resumed.store.resetNotice(),false);
const serialized=resumed.values.get('dj48.study-town.v1');resumed.store.beginPreview(E.create('hammer','expert'));resumed.store.get().unlocks.push('expert');resumed.store.get().stats[0].solved=99;resumed.store.record('tower',{room:24});resumed.store.switchSlot(2);resumed.store.save();assert.equal(resumed.store.isPreview(),true);assert.equal(resumed.values.get('dj48.study-town.v1'),serialized);resumed.store.endPreview();assert.equal(resumed.store.get().tower.weapon,'bow');assert.equal(resumed.store.get().stats[0].solved,0);
const failedWipe=keyedBoot([['dj48.fraction-world.v1',a.getRaw()]],true);assert.ok(failedWipe.values.has('dj48.fraction-world.v1'));assert.ok(failedWipe.store.warning());assert.equal(failedWipe.store.get().tower,null);
console.log('Study Town: one-time global legacy reset, all-slot isolation, failed-write protection, new save persistence and admin preview non-persistence passed.');
