'use strict';const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const D=require('../../public/fraction-world/study-domain'),E=require('../../public/fraction-world/expedition-domain'),C=require('../../public/fraction-world/content');
assert.equal(D.templates.length,90);assert.equal(new Set(D.templates.map(t=>t.id)).size,90);assert.equal(new Set(D.templates.map(t=>t.type)).size,9);for(const u of D.units)assert.equal(D.templates.filter(t=>t.unit===u.id).length,15);
for(const t of D.templates)for(let seed=0;seed<200;seed++){const q=D.generate(t.id,seed*7919),answers=Object.fromEntries(q.fields.map(f=>[f.id,f.answer]));assert.deepEqual(q,D.generate(t.id,seed*7919));const result=D.grade(q,answers);assert.equal(result.correct,t.type==='written'?null:true,t.id);if(t.type!=='written'){assert.ok(q.fields.length);for(const f of q.fields){const bad={...answers,[f.id]:'invalid'};assert.equal(D.grade(q,bad).correct,false,t.id);if(f.options){assert.equal(new Set(f.options).size,f.options.length);for(const a of Array.isArray(f.answer)?f.answer:[f.answer])assert.ok(f.options.includes(a),t.id);}if(f.kind==='fraction'){const [n,d]=f.answer.split('/').map(Number);assert.ok(n>0&&n%d>0,t.id);assert.ok(D.grade(q,{...answers,[f.id]:`${Math.floor(n/d)} ${n%d}/${d}`}).correct);}}}else assert.equal(q.rubric.length,3);}
// Independent arithmetic checks for the reverse-operation and two-step generators.
for(let seed=1;seed<100;seed++){let q=D.generate('decimal.restore',seed),final=Number(q.prompt.match(/(\d+\.35)L/)[1]);assert.ok(Math.abs(Number(q.fields[0].answer)-(final-.8+1.75))<1e-9);q=D.generate('triangle.iso',seed);assert.equal(Number(q.fields[0].answer)*2+q.visual.angle,180);q=D.generate('graph.increase',seed);const v=q.visual.values,g=v.slice(1).map((n,i)=>n-v[i]),segment=['월→화','화→수','수→목','목→금'][g.indexOf(Math.max(...g))];assert.equal(q.fields[0].answer,segment);q=D.generate('graph.total',seed);assert.equal(+q.fields[0].answer,q.visual.values[4]-q.visual.values[0]);}
const rng=D.random(918),levels=[0,0,0,0],recent=[];for(let i=0;i<10000;i++){const d=D.select(['decimal','polygon'],recent,false,rng),q=D.generate(d.template,d.seed);assert.ok(['decimal','polygon'].includes(q.unit));assert.notEqual(q.type,'written');levels[q.level]++;recent.push(d.template);if(recent.length>12)recent.shift();}assert.ok(levels[1]>1800&&levels[1]<2200);assert.ok(levels[2]>4700&&levels[2]<5300);assert.ok(levels[3]>2700&&levels[3]<3300);
const source=fs.readFileSync(require.resolve('../../public/fraction-world/store.js'),'utf8');function boot(raw){let saved=raw;const context={window:{FWExpedition:E,FWStudy:D},FWStudy:D,FWExpedition:E,FWContent:C,localStorage:{getItem:k=>k==='dj48.study-town.v1'?saved:null,setItem:(k,v)=>saved=v}};vm.runInNewContext(source,context);return {store:context.window.FWStore,raw:()=>saved};}
let b=boot(null),p=b.store.get();p.settings.studyUnits=['decimal','polygon'];p.stats[0]={attempts:2,first:1,solved:2};p.studyStats={'decimal.sum':{attempts:3,correct:2,submitted:0,partsCorrect:2,partsTotal:3}};p.quiz={engine:2,mode:'practice',count:10,index:1,title:'test',correct:1,wrong:0,units:['decimal'],recent:['decimal.sum'],answers:{a:'3.9'},question:{schema:2,template:'decimal.sum',seed:7},review:{status:'correct',correct:true,parts:[{id:'a',correct:true}]}};p.studyAnswers=[{id:'written',date:new Date().toISOString(),question:{schema:2,template:'decimal.writing',seed:8},status:'submitted',answer:'0.9는 0.90과 같아요.',selfCheck:[true,false,true]}];b.store.save();b=boot(b.raw());p=b.store.get();assert.equal(p.total,4);assert.equal(p.quiz.engine,2);assert.equal(p.quiz.review.correct,true);assert.equal(p.studyAnswers[0].answer,'0.9는 0.90과 같아요.');assert.equal(p.settings.studyUnits.length,2);b.store.switchSlot(1);assert.equal(Object.keys(b.store.get().studyStats).length,0);b.store.switchSlot(0);p=b.store.get();p.quiz.question.template='invalid';b.store.save();b=boot(b.raw());assert.equal(b.store.get().quiz,null);assert.equal(b.store.get().total,4);assert.equal(b.store.get().studyAnswers.length,1);
console.log('Study: 90 templates / 18,000 generations, 9 formats, independent arithmetic, 20/50/30 sampling, saved review and slot isolation PASS');
